### ISSUE TITLE
初始登录密码

### ISSUE THREAD

**Issue by yangzhipeng** [Clago/workflow#4]
你好，请问你的项目初始登录密码是什么啊

**Comment by Clago** [comment]
导入数据库文件,文件地址：database/sql/workflow_data.sql
初始账号: 1@qq.com 2@qq.com 3@qq.com 4@qq.com 5@qq.com 6@qq.com 7@qq.com 8@qq.com 9@qq.com 10@qq.com 密码统一为:123456
