### ISSUE TITLE
請教作者

### ISSUE THREAD

**Issue by tanxdx** [Clago/workflow#6]
ErrorException {#359 ▼
  #message: "Argument 2 passed to Workflow\Workflow::getProcessAuditorIds() must be an instance of Workflow\int, integer given, called in C:\wagon\uwamp\www\workflow-master\app\Service\Workflow\Workflow.php on line 89 and defined ◀"
  #code: 0
  #file: "C:\wagon\uwamp\www\workflow-master\app\Service\Workflow\Workflow.php"
  #line: 16
  #severity: E_RECOVERABLE_ERROR
  -trace: {▶}
}

請問這錯誤怎麼解決呢?

**Comment by Clago** [comment]
int类型限定导致的，低于7的不支持，限制去掉了。
