### ISSUE TITLE
請教作者2

### ISSUE THREAD

**Issue by tanxdx** [Clago/workflow#7]
不好意思
目前要輸入請假時出現以下資訊，要如何解決呢?
ErrorException {#346 ▼
  #message: "Trying to get property of non-object"
  #code: 0
  #file: "C:\wagon5\uwamp\www\workflow-master\app\Service\Workflow\Workflow.php"
  #line: 27
  #severity: E_NOTICE
  -trace: {▶}
}

**Comment by Clago** [comment]
应该是员工未设置主管导致的，这块已加了判断处理
